# Generated by Django 4.0.3 on 2022-10-23 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wish.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to=wish.models.get_audio_upload)),
                ('to_number', models.IntegerField(blank=True, null=True)),
                ('voise', models.CharField(blank=True, choices=[('person_name1', 'Person_name1'), ('person_name2', 'Person_name2'), ('person_name3', 'Person_name3')], max_length=40, null=True)),
                ('tarif', models.CharField(choices=[('standart', 'Standart'), ('premium', 'Premium')], default='standart', max_length=10)),
                ('status', models.CharField(choices=[('incompleted', 'Incompleted'), ('completed', 'Completed')], default='incompleted', max_length=15)),
                ('date_of_send', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
